/**
 * StyleFinder ID® reference data.
 *
 * Extracted from the StyleFinder source documents — the per-StyleType Elements
 * of Style cards and the per-archetype description sheets. This is the material
 * that grounds a generated Blueprint in the real system: without it the model
 * invents style icons, colors and shadow sides that do not belong to StyleFinder.
 *
 * Generated from those documents; edit them and re-extract rather than editing
 * the values here by hand.
 */

import type { StyleType } from './archetypes';

/** One StyleType's Elements of Style card. */
export interface StyleTypeReference {
  energy: 'Yang' | 'Yin';
  /** Vocabulary the system uses for this energy. */
  words: string;
  /** How this energy goes wrong when under- or over-expressed. */
  shadowSide: string;
  /** The one thing that matters most for this StyleType. */
  mostImportant: string;
  elements: string;
  colors: string;
  patterns: string;
  textures: string;
  silhouettes: string;
}

/** One archetype's description sheet. */
export interface ArchetypeReference {
  name: string;
  /** The three words the sheet leads with. */
  descriptor: string | null;
  /** Reference women named by the sheet. */
  styleIcons: string[];
  elements: string[];
  shadowSide: string[];
  /** The sheet's own style statement, in her voice. */
  statement: string | null;
  /** Wardrobe hallmarks named by the sheet. */
  hallmarks: string[];
  /** The sheet's Top 10 list. Empty where the source has it only as an image. */
  topTen: string[];
  /** The sheet's beauty-routine guidance. */
  beautyRoutine: string | null;
}

export const STYLE_TYPE_REFERENCE: Record<StyleType, StyleTypeReference> = {
  Classic: {
    energy: 'Yang',
    words: 'Timeless, elegant, refined, uncomplicated, sophisticated, cherished, honors tradition, intellectual, predictable, heritage, respectful, polished, opulent, reliable, tailored, architectural, understated, poised, gracious, composed, simplistic, enduring, cultivated, structured, composed',
    shadowSide: 'Looking dated, staying the same, looking boring, hiding your shape, looking matronly',
    mostImportant: 'Clothing that is timeless and transcends the trends',
    elements: 'Classic cuts, understated details, unfussy',
    colors: 'Neutrals, black, pastels, khaki, green, pink, medium tones, monochromatic looks',
    patterns: 'Stripes, polka dots, florals, plaids, herringbone',
    textures: 'Crisp, tailored, structure, soft structure',
    silhouettes: '',
  },
  Sporty: {
    energy: 'Yang',
    words: 'Fun, kinetic, highly energetic, reliable, active, casual, team player, proud, healthy, fit, athletic, comfortable, fresh, easy going, goal oriented, confident, relaxed, competitive, understated, informal movement genuine, harmonious',
    shadowSide: 'Frumpy, default style, hiding your shape, hiding out, sloppy, lack of style',
    mostImportant: 'Physical comfort is paramount, whether dressed for the gym or the boardroom',
    elements: 'Stretch, ease, comfort, flow, flexible',
    colors: 'Black, white, gray, yellow, optic brights',
    patterns: 'Stripes, graphic designs',
    textures: 'Stretch, smooth, shiny',
    silhouettes: 'Fitted, close to the body',
  },
  Dramatic: {
    energy: 'Yang',
    words: 'Avant-garde, unique, innovative, strong, exciting, Passionate, presence, modern, powerful, daring, Cutting edge, singular, mysterious, driven, striking, Flamboyant, statement, free-spirit, purposeful, elemental, Change-agent, rebel, creative, stature, elegant, Pioneer, exotic, controversial, authority, graceful, Experimental, maverick, bold, artisan',
    shadowSide: 'Trying too hard, letting clothes wear you or overwhelm you, wearing something inappropriate, posing as something you’re not',
    mostImportant: 'The, Dramatic woman wants to be noticed. No wallflower, she chooses clothing that is bold, cutting-edge and expresses her individuality. Standing out and wearing something that makes a statement is her modus operandi, and she often chooses things for their shock value',
    elements: '',
    colors: 'The dramatic woman often has dramatic coloring, whether natural or chemically enhanced, and looks best in primary colors, rich bold jewel tones, black and white. Metallics, Pastels are not for the dramatic woman, Design, Lines: Sculptural, Cuts, Long jackets over shorter skirts, Asymmetrical lines, modern edge, Columnar shapes, Angular, Accessories: Look for avante-garde',
    patterns: 'Abstract prints, Optic prints, geometric prints, color blocking, bold stripes and dots, bold animal prints, solid black',
    textures: 'Opulent fabrics, swooping layers, crisp details, sheer cutouts, shiny surfaces, studded, rough, distressed',
    silhouettes: '',
  },
  Contemporary: {
    energy: 'Yang',
    words: 'Modern, innovative, energetic, discerning, sexy, current, hipster, fun, chic, status, designer, leading edge, stylish, in style, up to the minute, trendy, fashionista, luxury, elegant, powerful, vivacious, magnetic',
    shadowSide: 'Trying too hard, keeping up with the, Joneses, sameness, being label-conscious',
    mostImportant: 'Wearing what’s hot and in style, wearing the season’s best colors, looking on-trend',
    elements: 'Pairing trendy items with timeless pieces, designer handbag and shoes',
    colors: 'Blue, red, black, green, gold, metallic, brown',
    patterns: 'Bold, colorful prints, abstract, stripes, dots, floral, color blocks',
    textures: 'Sheer, smooth, denim',
    silhouettes: 'Columnar, flowy, sleek, tailored, structure',
  },
  Natural: {
    energy: 'Yin',
    words: 'Nurturing, organic, hand-crafted, homespun, easy going, comfortable, authentic, reliable, unconventional, free-spirit, eco-friendly, conscious, enlightened, fresh, creative, practical, energetic, intuitive, relaxed rustic sacred understated',
    shadowSide: 'Looking frumpy, boring, plain, wearing oversized clothing that hides your shape',
    mostImportant: 'Wearing natural fibers, fabrics that feel good to the touch and comfortable against the skin',
    elements: 'Natural fibers, soft textures and elements that feel good',
    colors: 'Green, ivory, beige, muted colors',
    patterns: 'Florals, abstract, swirls',
    textures: 'Nubby, rough, flowy, sheer, layered, embroidered, hand stitched, elastic',
    silhouettes: 'Flowy, layered, relaxed, unstructured',
  },
  Whimsical: {
    energy: 'Yin',
    words: 'Playful, fun, mismatched, layered, cute, colorful, spirited, rich, energetic, creative, excite, intrigue, interesting, multi-faceted, surprise, delight, indulge, decadent, eclectic, regal, whimsy, unexpected, youthful, fantasy, innovative, bold, curious',
    shadowSide: 'Looking silly, dressing too youthful, overkill, being label- conscious',
    mostImportant: 'Fun and surprise',
    elements: 'Mix things in new and different ways. Ask yourself what’s unexpected?',
    colors: 'Vibrant, multi-colored, brights, pastels and neutrals and blended together and mixed in unexpected ways',
    patterns: 'Polka dots, stripes, floral, swirls, medium to small animal prints, colorful patchwork, butterflies, insects',
    textures: 'Ribbed, nubby, lustrous, sensuous, soft, beaded, ribbons',
    silhouettes: 'Boxy, short, layered, defined, style lines, short over long, curved, playful shapes such as animals or flowers',
  },
  Delicate: {
    energy: 'Yin',
    words: 'Refined, sweet, thoughtful, understated, sensitive, cute, quiet, playful, dainty, soft, relaxed, demure, tasteful, reserved, precise, unfussy, petite feminine cultivated',
    shadowSide: 'Childlike, dressing too young, being overpowered by clothes or shapes, getting lost',
    mostImportant: 'Undeniably feminine yet understated',
    elements: 'Feminine with a touch of girlish charm, pretty, sleek',
    colors: 'Ivory, beige, muted colors, pastels',
    patterns: 'Tiny prints, ditsy prints, polka dots, thin stripes, hearts, flowers',
    textures: 'Soft, flowy, smooth',
    silhouettes: 'Curved, untailored, details',
  },
  Romantic: {
    energy: 'Yin',
    words: 'Flowing, bohemian, spirit of the southwest, angelic, sensual, nostalgic, vintage, ruffles, flourish, sweet, feminine, pretty, a little bit country, flirtatious, charming, soft, charismatic, impulsive, sentimental graceful history cherish',
    shadowSide: 'too much of a good thing, overpowering looks, overdone makeup, overkill',
    mostImportant: 'Unabashedly feminine, sense of history, items that tell a story',
    elements: 'Flounces, ruffles, lace, vintage inspired charm, nostalgia',
    colors: 'Dark, purple, pink, black, caramel, teal, taupe, gray, metallic',
    patterns: 'Floral, dots, stripes, mixed patterns',
    textures: 'Lace, sheer, fluid, flowy',
    silhouettes: 'Contoured, full, flowy, soft, rounded',
  },
};

/** Keyed `${primary}/${secondary}`, matching ARCHETYPES. */

export const ARCHETYPE_REFERENCE: Record<string, ArchetypeReference> = {
  'Classic/Delicate': {
    name: 'The Gracious',
    descriptor: 'Ladylike, reserved, demure',
    styleIcons: [
      'Princess Diana',
      'Giada DeLaurentis',
      'Rachel Bilson',
      'Grace Kelly',
      'Natalie Portman',
    ],
    elements: [
      'Understated Femininity',
      'Timeless Style',
      'Relaxed structure',
      'Elegance',
    ],
    shadowSide: [
      'Looking too young or too old',
      'Looking dated',
      'Looking boring',
      'Hiding your shape',
    ],
    statement: 'Understated Elegance',
    hallmarks: [
      'A sense of heritage and sophistication are how the Gracious rolls, and wearing family heirlooms is par for the course',
      'Grandmother’s pearls, your mother’s ring, your father’s sweater, that scarf you bought in Paris, are all ways to create connections with your life and lineage and hold up the ideals of the',
      'Classics. Soft colors, luxurious fabrics and delicate details are your hallmarks',
    ],
    topTen: [],
    beautyRoutine: 'The Gracious prefers to celebrate her beauty with soft, pretty makeup and a hairstyle that works with what she has naturally, rather than relying too heavily on makeup and styling products. Your look is subtle, yet polished Silky blouse — soft drape, delicate details Beautifully tailored trousers Softly feminine dress — pastels, subtle prints or delicate detailing Perfect-fitting jeans — clean, classic wash Feminine tailored coat Lace or delicately detailed top Kitten heels or elegant flats Graceful skirt — A-line, pleated or softly flowing Heirloom-inspired jewelry — pearls, lockets, delicate',
  },
  'Classic/Natural': {
    name: 'The Genuine',
    descriptor: 'Refined, Authentic, Prestige',
    styleIcons: [
      'Jackie Kennedy',
      'Katie Holmes',
      'Michelle Obama',
      'Kate Middleton',
    ],
    elements: [
      'Timeless Styling',
      'Understated details',
      'Relaxed structure',
      'Fabrics that feel good',
    ],
    shadowSide: [
      'Looking matronly',
      'Looking boring',
      'Looking dated',
      'Hiding your shape',
    ],
    statement: 'Simple Elegance',
    hallmarks: [
      'A sense of heritage and prestige are how the Genuines roll, and wearing family heirlooms is par for the course',
      'Grandmother’s pearls, your mother’s ring, your father’s sweater, that scarf you bought in Paris, are all ways to create connections with your life and lineage and hold up the ideals of the',
      'Classic',
    ],
    topTen: [
      'Button down Blouses',
      'Tailored trousers',
      'Classic Blazer',
      'Great fitting classic jeans',
      'A Timeless Trench coat',
      'Simple Shift Dress',
      'Twinsets',
      'Pumps & Ballet Flats',
      'Heirloom jewelry & Accessories',
      'Investment handbag',
    ],
    beautyRoutine: 'Makeup should be simple and elegant, favoring timeless colors such as pink, coral, nude or red lips and nails and colors that play up features without being overly dramatic Hair is cut in a flattering style that is up to date, but not trendy. Low maintenance, your look is simple yet elegant',
  },
  'Classic/Romantic': {
    name: 'The Sentimental',
    descriptor: 'Understated, Nostalgic, Elegant',
    styleIcons: [
      'Anne Hathaway',
      'Rachel Weisz',
      'Lily Collins',
      'Marion Cotillard',
    ],
    elements: [
      'Unabashedly Feminine',
      'Timeless Style',
      'Relaxed structure',
      'Elegance',
    ],
    shadowSide: [
      'Looking overdone',
      'Looking dated',
      'Looking frumpy',
      'Hiding your shape',
    ],
    statement: 'Feminine Elegance',
    hallmarks: [
      'A sense of heritage and femininity are how the Sentimental rolls, and wearing family heirlooms is par for the course',
      'Grandmother’s pearls, your mother’s ring, your father’s sweater, that scarf you bought in Paris, are all ways to create connections with your life and lineage and hold up the ideals of the',
      'Classics',
    ],
    topTen: [],
    beautyRoutine: 'Opt for a clean, classic hairstyle that works with your hair and has soft movement. Long hair is ideal, as is a tousled shorter look. Avoid a hairstyle that is too harsh Pretty, soft makeup works best for you Understated, nude shades Look for the hot colors each season and wear your best understated versions of them Silky blouse — drape, sheen or subtle romantic detailing Softly tailored trousers — elegant rather than severe Beautiful feminine dress — florals, graceful shapes, vintage-inspired details Perfect-fitting jeans — classic wash, feminine silhouette Feminine coat — belted, shaped or b',
  },
  'Classic/Whimsical': {
    name: 'The Adventurer',
    descriptor: 'Sophisticated, Polished, Creative',
    styleIcons: [
      'Diane Keaton',
      'Jenna Lyons',
      'Audrey Hepburn',
      'Olivia Palermo',
    ],
    elements: [
      'Fun & Surprise',
      'Timeless Style',
      'Relaxed structure',
      'Something Unexpected',
    ],
    shadowSide: [
      'Looking too young or too old',
      'Looking silly',
      'Looking dated',
      'Hiding your shape',
    ],
    statement: 'Classic with a Twist',
    hallmarks: [
      'A sense of fun and surprise are how the',
      'Adventurers roll, mixing family heirlooms with inexpensive items, blending neutrals in unexpected ways and pairing prints and vibrant colors in a way that is refined and understated, yet playful',
    ],
    topTen: [
      'Solid Blouses',
      'Tailored trousers',
      'Classic Blazer',
      'Playful Accessories',
      'A Timeless Trench coat in a',
      'bright color',
      'Little Black Dress (blue, teal…)',
      'Leopard print flats',
      'Boots and loafers',
      'Heirloom jewelry',
      'Investment handbag',
      'StyleFinder ID® System',
    ],
    beautyRoutine: 'Makeup should be simple and elegant, favoring timeless colors that play up features without being overly dramatic Hair is cut in a flattering style that is up to date, but not trendy. Low maintenance, your look is simple yet elegant',
  },
  'Contemporary/Delicate': {
    name: 'The Cosmopolitan',
    descriptor: 'Modern, Refined, Unfussy',
    styleIcons: [
      'Jane Birkin',
      'Naomi Watts',
      'Carolyn Bessette-Kennedy',
      'Katie Holmes',
    ],
    elements: [
      'Up to the minute style',
      'Latest colors and trends',
      'Understated look',
      'Undeniably Feminine',
    ],
    shadowSide: [
      'Dressing too youthful',
      'Being overpowered by clothing',
      'Being label-conscious',
      'Getting lost',
      'Keeping up with the Joneses',
    ],
    statement: 'Fashionably Understated',
    hallmarks: [
      'Trendy, yet feminine is your style. You love to get dressed and look forward to experimenting with things in new and different ways. You’re one to watch and your friends take note, but you make sure to temper your look to be delicate and not overpowering. You never let the trends wear you',
    ],
    topTen: [],
    beautyRoutine: 'Your hairstyle is influenced by the latest trends, yet with a ladylike charm Think understated Makeup is polished, but never sacrifice your personal best colors for what’s in style. Play up your best features with soft, pretty colors that complement your personal coloring Refined feminine tops — clean lines, subtle details, beautiful fabrics Slim ankle-length trousers — sleek and modern Modern blazer — streamlined rather than traditionally tailored Chic cardigan or fine-gauge knit — simple, soft and polished Sleek pumps or kitten heels — feminine without fussiness Simple modern dress — clean s',
  },
  'Contemporary/Natural': {
    name: 'The Polished',
    descriptor: 'Elegant, Unconventional, Relaxed',
    styleIcons: [
      'Lauren Hutton',
      'Gisele Bundchen',
      'Naomi Watts',
      'Jennifer Aniston',
    ],
    elements: [
      'Up to the minute style',
      'Latest colors and trends',
      'Wearing fabrics that feel good',
      'Relaxed structure',
    ],
    shadowSide: [
      'Trying too hard',
      'Looking frumpy',
      'Hiding your shape',
      'Keeping up with the Joneses',
    ],
    statement: 'Relaxed Chic',
    hallmarks: [
      'Trendy, yet approachable is your style',
      'You like to wear a polished version of jeans and a t, spicing it up with designer shoes and jewelry that keeps your look on trend. When dressing up, you choose items that are sleek, but maintain the comfort factor',
    ],
    topTen: [],
    beautyRoutine: 'Opt for a soft, simple hairstyle that is eye-catching yet doesn’t require a lot of maintenance and keeps you looking on trend Your makeup is polished, yet understated, never overpowering you Keep your colors in the nudes and neutrals range with an occasional pop of color Modern statement top — asymmetric, architectural, draped, or unexpected detail Relaxed modern jeans — straight, wide-leg, barrel, or boyfriend Unstructured blazer — polished but easy, slightly oversized Longline or cocoon cardigan — clean, contemporary shape Sleek loafers or modern flats — polished without feeling fussy Minima',
  },
  'Contemporary/Romantic': {
    name: 'The Superstar',
    descriptor: 'Powerful, Sexy, Charismatic',
    styleIcons: [
      'Beyonce Knowles',
      'Goldie Hawn',
      'Tyra Banks',
      'Farrah Fawcett',
      'Jennifer Lopez',
    ],
    elements: [
      'Wearing what’s on trend',
      'Wearing current colors',
      'Feminine looks',
      'Sense of history',
    ],
    shadowSide: [
      'Trying too hard',
      'Anything overdone',
      'Too much of a good thing',
      'Keeping up with the Joneses',
    ],
    statement: 'Modern Glamour',
    hallmarks: [
      'Trendy, yet feminine is your style. You like to wear a polished version of jeans and a t, spicing it up with sexy shoes and jewelry that keeps your look on trend. When dressing up, you choose items that are sleek, yet have a feminine charm',
    ],
    topTen: [],
    beautyRoutine: 'Opt for a soft, pretty hairstyle that is eye-catching yet feminine. Softly tousled curls, or hair that has movement will flatter you best Nothing harsh, stiff or ‘crunchy’ will do Your makeup is polished, yet understated, never overpowering you Wear colors that speak to your romantic side, yet never look overdone Avoid a heavy ‘made-up’ look',
  },
  'Contemporary/Whimsical': {
    name: 'The Trendsetter',
    descriptor: 'Luxury, Stylish, Surprise',
    styleIcons: [
      'Kim Kardashian',
      'Kate Moss',
      'Olivia Palermo',
      'Alexa Chung',
    ],
    elements: [
      'Up to the minute style',
      'Latest colors and trends',
      'Something Fun',
      'Unexpected combinations',
    ],
    shadowSide: [
      'Trying too hard',
      'Looking frumpy',
      'Hiding your shape',
      'Keeping up with the Joneses',
    ],
    statement: 'Stylish Surprise',
    hallmarks: [
      'Trendy, yet fun is your style. You love to get dressed and look forward to experimenting with things in new and different ways. You’re one to watch and your friends take note',
    ],
    topTen: [],
    beautyRoutine: 'Your hairstyle is influenced by the latest trends, with highlights and bold color Makeup is polished, but never sacrifice your personal best colors for what’s in style. Play up your best features with fun colors that complement your personal coloring Statement top — embellishment, unusual details, print, or unexpected shape Modern trousers — wide-leg, cropped, barrel, or an interesting silhouette Patterned or statement jacket — distinctive color, texture, print, or cut Fashion-forward cardigan — cropped, embellished, oversized, or uniquely detailed Statement shoes — an unexpected color, shape,',
  },
  'Delicate/Classic': {
    name: 'The Darling',
    descriptor: 'Feminine, Refined, Sweet',
    styleIcons: [
      'Audrey Hepburn',
      'Natalie Portman',
      'Lily Collins',
      'Emmy Rossum',
      'Grace Kelly',
    ],
    elements: [
      'Delicate femininity',
      'Refined details',
      'Timeless silhouettes',
      'Soft sophistication',
    ],
    shadowSide: [
      'Looking too girlish',
      'Looking overly conservative',
      'Fading into the background',
      'Looking dated or overly precious',
    ],
    statement: 'Timeless Femininity',
    hallmarks: [
      'Graceful femininity is your calling card. Soft c embellishment and beautifully refined accessorie appreciate pieces with heritage and meaning—p crafted classics—but your overall effect is lighter hallmarks emphasize heritage and sophistication',
    ],
    topTen: [
      'Delicate silky blouse',
      'Softly tailored trousers',
      'Pretty feminine dress',
      'Fine-knit cardigan',
      'Feminine tailored coat',
      'Lace or delicately detailed top',
      'Kitten heels or elegant flats',
      'Graceful A-line or pleated skirt',
      'Delicate heirloom jewelry',
      'Refined ladylike handbag',
    ],
    beautyRoutine: 'Soft, pretty and polished is your ideal. Choose na defined eyes, rosy cheeks and a flattering lip Hair should feel graceful and feminine rather th a simple chignon or a naturally pretty cut that fra',
  },
  'Delicate/Contemporary': {
    name: 'The Understated',
    descriptor: 'Refined, Feminine, Modern',
    styleIcons: [
      'Naomi Watts',
      'Carolyn Bessette-Kennedy',
      'Katie Holmes',
      'Gwyneth Paltrow',
      'Felicity Jones',
    ],
    elements: [
      'Understated femininity',
      'Modern simplicity',
      'Refined details',
      'Current accents',
    ],
    shadowSide: [
      'Fading into the background',
      'Looking too plain',
      'Being overpowered by trends',
      'Dressing too youthful',
      'Playing it too safe',
    ],
    statement: 'Quietly Chic',
    hallmarks: [
      'Quiet sophistication is your hallmark. You fav color combinations and delicate details, punctua never fussy or overly embellished, but they\'re ne',
      'The Cosmopolitan loves experimenting with tren delicate quality. For The Understated, that balanc simply the finishing touch',
    ],
    topTen: [
      'Refined feminine top',
      'Slim ankle-length trousers',
      'Soft modern blazer',
      'Fine-gauge knit or cardigan',
      'Sleek kitten heels or flats',
      'Simple modern dress',
      'Chic contemporary sunglasses',
      'Streamlined coat',
      'Delicate modern jewelry',
    ],
    beautyRoutine: 'Your beauty look is soft, polished and modern flattering colors rather than heavy makeup or obv Hair should feel current but uncomplicated—a sl simple style with beautiful movement. Think effo styled',
  },
  'Delicate/Dramatic': {
    name: 'The Primadonna',
    descriptor: 'Exquisite, Captivating, Dramatic',
    styleIcons: [
      'Lily Collins',
      'Audrey Hepburn',
      'Rooney Mara',
      'Anya Taylor-Joy',
      'Winona Ryder',
    ],
    elements: [
      'Exquisite details',
      'Feminine silhouettes',
      'High contrast',
      'Dramatic accents',
    ],
    shadowSide: [
      'Looking too precious',
      'Letting clothes overpower you',
      'Trying too hard',
      'Looking overly theatrical',
    ],
    statement: 'Exquisite Drama',
    hallmarks: [],
    topTen: [
      'Exquisitely detailed blouse',
      'Lace or sheer-detail dress',
      'Cropped statement jacket',
      'Tulle or ethereal skirt',
      'Sleek tailored trousers',
      'Dramatic pointed-toe shoes',
      'Delicate statement jewelry',
      'Feminine structured clutch',
      'Statement coat',
      'Satin camisole',
    ],
    beautyRoutine: 'Beauty is part of your expression. Keep your ove afraid of a dramatic detail—a defined eye, bold li Hair should feel polished and feminine with an el elegant updo or another beautifully groomed styl overwhelming them',
  },
  'Delicate/Sporty': {
    name: 'The Informal',
    descriptor: 'Soft, Casual, Unassuming',
    styleIcons: [
      'Michelle Williams',
      'Kristen Bell',
      'Reese Witherspoon',
      'Meg Ryan',
      'Amy Adams',
    ],
    elements: [
      'Understated femininity',
      'Soft details',
      'Comfortable fabrics',
      'Casual ease',
    ],
    shadowSide: [
      'Looking too youthful',
      'Looking frumpy',
      'Fading into the background',
      'Sacrificing style for comfort',
      'Being overpowered by clothing',
    ],
    statement: 'Casual Femininity',
    hallmarks: [
      'Your signature is easy femininity—soft knits, de layers and uncomplicated silhouettes. You want very little fuss',
      'The Sporty/Delicate template emphasizes easy-c relaxed jackets. For The Informal, I\'d keep those softer, lighter and more feminine',
    ],
    topTen: [
      'Delicate knit tops',
      'Fine-knit cardigan',
      'Great-fitting jeans',
      'Simple jersey dress',
      'Soft stretch pants',
      'Pretty sneakers',
      'Feminine casual flats',
      'Lightweight relaxed jacket',
      'Soft casual skirt',
      'Easy crossbody bag',
    ],
    beautyRoutine: 'Keep your beauty routine fresh, soft and uncom blush, mascara and a pretty lip may be all you ne Choose an easy-care hairstyle with softness and sprayed, sculpted or “done.” Your goal is pretty w',
  },
  'Dramatic/Delicate': {
    name: 'The Demure Diva',
    descriptor: 'Mysterious, Refined, Exciting',
    styleIcons: [
      'Gennifer Goodwin',
      'Tina Fey',
      'Mae West',
      'Dita von Teese',
    ],
    elements: [
      'Sculptural Cuts',
      'Girlish charm',
      'Soft Details',
      'Sleek lines',
    ],
    shadowSide: [
      'Trying too hard',
      'Looking childlike',
      'Hiding your shape',
      'Letting clothes wear you',
    ],
    statement: 'Boldly Feminine',
    hallmarks: [
      'Her style is refined femininity with an unexpected edge—sleek silhouettes, high contrast, delicate fabrics, exquisite details and one striking element that creates intrigue',
      'She is polished and feminine, but never overly sweet: delicate, mysterious and quietly dramatic',
    ],
    topTen: [],
    beautyRoutine: 'An elegantly striking hairstyle suits you Whether it’s natural or dyed a vibrant bright, keep your style sleek and well-groomed You like to have fun with makeup and your dramatic sensibility makes it easier for you to wear bright and deep hues Sculptural jacket Lace or sheer-detail dress Dramatic ruffled blouse Tulle or ethereal skirt Cropped statement jacket Feminine structured clutch Delicate statement bracelet Diamond studs Glamorous shoes Satin camisole',
  },
  'Dramatic/Natural': {
    name: 'The Bon Vivant',
    descriptor: 'Free-spirit – Enlightened - Innovative',
    styleIcons: [
      'Donna Karan',
      'Lupita Nyong’o',
      'Tilda Swinton',
      'Linda Rodin',
    ],
    elements: [
      'Sculptural Cuts',
      'Natural Fibers',
      'Minimalist Details',
      'Soft Textures',
    ],
    shadowSide: [
      'Trying too hard',
      'Looking frumpy',
      'Hiding your shape',
      'Letting clothes wear you',
    ],
    statement: 'Artful Ease',
    hallmarks: [
      'Sculptural simplicity is how you roll, opting for unique items that stand out, yet are anything but fussy. Pair a bold jacket with relaxed-fit trousers or jeans, and team with an easy-fit cotton tee',
      'You prefer timeless cuts paired in sophisticated ways, and you like to wear combinations that no one else would put together. Simple, hand-wrought jewelry punctuates your look with a',
    ],
    topTen: [
      'Sculptural jacket',
      'Softly structured trousers',
      'Cotton tops and tees',
      'Well-fitting jeans',
      'Asymmetrical skirt',
      'Relaxed fitting coat',
      'Sculptural shoes',
      'Architectural dress',
      'Hand-wrought jewelry',
      'Rustic leather handbag',
    ],
    beautyRoutine: 'Opt for a bold, yet simple hairstyle that is eye-catching yet doesn’t require a lot of maintenance Mineral makeup is perfect for your natural sensibility, with some darker hues and striking color combinations',
  },
  'Dramatic/Romantic': {
    name: 'The Sensualist',
    descriptor: 'Magnetic – Sophisticated – Seductive',
    styleIcons: [
      'Monica Bellucci',
      'Sophia Loren',
      'Catherine Zeta-Jones',
      'Salma Hayek',
    ],
    elements: [
      'Sensuous Silhouettes',
      'Luxurious Fabrics',
      'Dramatic Details',
      'Rich Color',
    ],
    shadowSide: [
      'Overdoing the sex appeal',
      'Looking overly glamorous',
      'Mistaking tight for sensual',
      'Hiding your sensuality to fit in',
    ],
    statement: 'Magnetic Allure',
    hallmarks: [
      'Sophisticated sensuality is your signature. Yo curves, luxurious textures and dramatic details. A coat or fabulous shoe makes you feel like yourse creating an air of confidence, mystery and unden',
    ],
    topTen: [
      'Body-skimming dress',
      'Silk or satin blouse',
      'Dramatic fitted jacket',
      'High-waisted trousers',
      'Pencil or draped skirt',
      'Statement coat',
      'Glamorous heels or boots',
      'Lace or sheer-detail top',
      'Bold statement jewelry',
      'Luxurious structured handbag',
    ],
    beautyRoutine: 'Embrace polished glamour with luminous skin, d feminine and intentional—glossy waves, a sleek sensual and polished rather than overly perfe',
  },
  'Dramatic/Whimsical': {
    name: 'The Ingenue',
    descriptor: 'Strong, Playful, Elegant',
    styleIcons: [
      'Isabella Blow',
      'Pink!',
      'Tina Chow',
      'Tracee Ellis Ross',
      'Lady Gaga',
    ],
    elements: [
      'Sculptural Cuts',
      'Playful Combinations',
      'Bold Details',
      'Colorful Items',
      'Conversation pieces',
    ],
    shadowSide: [
      'Trying too hard',
      'Looking frumpy',
      'Hiding your shape',
      'Letting clothes wear you',
    ],
    statement: 'Spirited Elegance',
    hallmarks: [
      'Black and neutrals mixed together in unexpected ways. Think about teaming up a matte with a metallic in the same hue, or pairing different textures and prints together in the same outfit',
      'Always have a focal point of your outfit, whether it’s your shoes, your handbag or your dress, and let it take center stage. While your look is bold, avoid overwhelm',
    ],
    topTen: [
      'Sculptural jacket',
      'Bold printed pants',
      'Graphic tops and tees',
      'Colored denim',
      'Asymmetrical skirt',
      'Conversation-starting handbag',
      'Mixed-media shoes',
      'Architectural jewelry',
      'Colorful lace or embellished top',
      'Statement coat in a bold hue',
      'StyleFinder Copyright 2016',
      'www.ShopStyleFinder.com',
    ],
    beautyRoutine: 'An elegantly striking hairstyle suits you Whether it’s natural or dyed a vibrant bright, keep your style sleek and well-groomed You like to have fun with makeup and your dramatic sensibility makes it easier for you to wear bright and deep hues',
  },
  'Natural/Classic': {
    name: 'The Girl Next Door',
    descriptor: 'Fresh, Timeless, Genuine',
    styleIcons: [
      'Katie Couric',
      'Julie Roberts',
      'Mia Farrow',
      'Liz Lange',
    ],
    elements: [
      'Fabrics with Stretch',
      'Natural Fibers',
      'Timeless Pieces',
      'Functional Items',
    ],
    shadowSide: [
      'Looking boring',
      'Looking frumpy',
      'Hiding your shape',
    ],
    statement: 'Easy Care, Easy Wear',
    hallmarks: [
      'Easy care separates that are machine wash, wrinkle resistant',
      'Functional shoes – flat',
      'Light and medium colors',
      'Matte surfaces – avoid anything too shiny such as patent leather',
      'Natural fibers',
      'Relaxed jackets',
      'Easy fit, avoiding anything that is restricting',
    ],
    topTen: [
      'Trench coat',
      'Ponte Knit Blazers',
      'Flowing Cardigan',
      'Boyfriend Jeans',
      'Relaxed tops',
      'Jersey Dress',
      'Flats and Pumps',
      'Easy fit pants',
      'Great Watch',
      'Durable handbag',
    ],
    beautyRoutine: 'Not one to be restricted by clothing or by life, the Girl Next Door prefers to celebrate her natural beauty with simple makeup and easy-care hair, rather than relying too heavily on makeup and styling products. Just a touch is all you need to keep you feeling fresh and polished',
  },
  'Natural/Contemporary': {
    name: 'The Essential',
    descriptor: 'Sexy, Easy-going, Stylish',
    styleIcons: [
      'Gwyneth Paltrow',
      'Jennifer Lawrence',
      'Alicia Silverstone',
      'Julianne Moore',
    ],
    elements: [
      'Wearing the best colors',
      'Natural Fibers',
      'Looking on-trend',
      'Luxurious fabrics',
    ],
    shadowSide: [
      'Looking boring',
      'Looking frumpy',
      'Trying too hard',
      'Hiding your shape',
    ],
    statement: 'Relaxed Polish',
    hallmarks: [
      'Sensuous, natural fibers including cotton, cashmere, silk, rayon and other manmade fibers that feel good to the touch',
      'Jewelry, shoes and handbags that are up to the minute',
      'Items that are:',
      'functional, yet stylish that feel good to the touch are lightweight and comfortable',
    ],
    topTen: [
      'Leggings or ponte knit pants',
      'Jeans with stretch',
      'Scarves in statement colors',
      'Chic, easy-fit tops',
      'On-trend jewelry',
      'Current, comfortable shoes',
      'Designer or elevated handbag',
      'Investment jacket',
      'Chic statement coat',
      'Relaxed modern dress',
    ],
    beautyRoutine: 'Your hair is cut in a style that is on trend, whether short or long, and is low-maintenance. Highlights or lowlights add dimension Your makeup is soft and understated with a bold lip or a smoky eye',
  },
  'Natural/Dramatic': {
    name: 'The Artiste',
    descriptor: 'Authentic, Innovative, Unconventional',
    styleIcons: [
      'Georgia O’Keefe',
      'Norma Kamali',
      'Vera Wang',
      'Anne Hathaway',
    ],
    elements: [
      'Sculptural Cuts',
      'Natural Fibers',
      'Minimalist Details',
      'Soft Textures',
    ],
    shadowSide: [
      'Trying too hard',
      'Looking frumpy',
      'Hiding your shape',
      'Letting clothes wear you',
    ],
    statement: 'Sculptural Simplicity',
    hallmarks: [
      'Sculptural simplicity is how you roll, opting for unique items that stand out, yet are anything but fussy. Pair a bold jacket with relaxed-fit trousers or jeans, and team with an easy-fit cotton tee',
      'Hand-dyed scarves, handcrafted vests and jackets and anything with a unique, artisanal touch mark your style. Simple, hand-wrought jewelry punctuates your look with a bold statement',
    ],
    topTen: [
      'Sculptural jacket',
      'Modern-fit pants',
      'Elevated cotton tops & tees',
      'Well-fitting jeans',
      'Asymmetrical skirt',
      'Relaxed statement coat',
      'Sculptural shoes',
      'Architectural dress',
      'Hand-wrought jewelry',
      'Rustic leather handbag',
    ],
    beautyRoutine: 'Opt for a bold, yet simple hairstyle that is eye-catching yet doesn’t require a lot of maintenance Mineral makeup is perfect for your natural sensibility, with some darker hues and striking color combinations',
  },
  'Natural/Sporty': {
    name: 'The Easy Going',
    descriptor: 'Relaxed, Unfussy, Warm',
    styleIcons: [
      'Cameron Diaz',
      'Sienna Miller',
      'Jennifer Aniston',
      'Lauren Hutton',
    ],
    elements: [
      'Fabrics with Stretch',
      'Natural Fibers',
      'Comfort',
      'Ease',
    ],
    shadowSide: [
      'Looking boring',
      'Looking frumpy',
      'Hiding your shape',
    ],
    statement: 'Form + Function',
    hallmarks: [
      'Easy care separates that are machine wash, wrinkle resistant',
      'Functional shoes – flat',
      'Light and medium colors',
      'Matte surfaces – avoid anything too shiny such as patent leather',
      'Natural fibers',
      'Relaxed jackets',
      'Easy fit, avoiding anything that is restricting',
    ],
    topTen: [
      'Ponte knit pants',
      'Ponte knit blazer',
      'Flowing cardigan',
      'Relaxed-fit jeans',
      'Easy knit tops',
      'Jersey dress',
      'Athletic-inspired flats',
      'Comfortable casual shoes',
      'Lightweight anorak',
      'Crossbody bag',
    ],
    beautyRoutine: 'Not one to be restricted by clothing or by life, the Easy Going prefers to celebrate her natural beauty with simple makeup and easy-care hair, rather than relying too heavily on makeup and styling products. Just a touch is all you need to keep you feeling fresh and polished',
  },
  'Romantic/Classic': {
    name: 'The Nostalgic',
    descriptor: 'Timeless, Charming, Sentimental',
    styleIcons: [
      'Diane Lane',
      'Michelle Pfeiffer',
      'Kate Winslet',
      'Marcia Cross',
    ],
    elements: [
      'Unabashed Femininity',
      'Timeless cuts',
      'Items that tell a story',
      'Vintage Inspiration',
    ],
    shadowSide: [
      'Trying too hard',
      'Overkill',
      'Hiding your shape',
      'Looking Dated',
      'Looking Matronly',
    ],
    statement: 'Sentimental Sophistication',
    hallmarks: [
      'Heirloom Jewelry',
      'Florals, mixed prints',
      'Medium tones',
      'Timeless cuts',
      'Layers',
      'Understated styles',
    ],
    topTen: [
      'Ruffled blouse',
      'Romantic floral dress',
      'Embellished tops',
      'Elegant trousers',
      'Feminine coat',
      'Lace-detail top',
      'Vintage-inspired boots',
      'Long, flowing skirt',
      'Heirloom jewelry & accessories',
      'Vintage or vintage-inspired',
      'handbag',
      'StyleFinder Copyright 2016',
    ],
    beautyRoutine: 'Long hair with curls or a shorter, tousled look keep you in touch with your feminine side. Avoid a hairstyle that is too harsh Pretty, soft makeup works best Understated, nude shades punctuated with plums, purples and mauves for lips, cheeks and nails Timeless, not trendy Keep your look understated and sophisticated',
  },
  'Romantic/Contemporary': {
    name: 'The Charmer',
    descriptor: 'Alluring, Stylish, Irresistible',
    styleIcons: [
      'Blake Lively',
      'Sofia Vergara',
      'Kate Hudson',
      'Jennifer Aniston',
      'Eva Mendes',
    ],
    elements: [
      'Feminine silhouettes',
      'Sensual details',
      'Current trends',
      'Luxurious fabrics',
    ],
    shadowSide: [
      'Looking overly sexy',
      'Trying too hard',
      'Too much femininity',
      'Chasing trends that don’t flatter',
    ],
    statement: 'Modern Romance',
    hallmarks: [],
    topTen: [
      'Romantic statement blouse',
      'Sleek dark-wash jeans',
      'Feminine fitted blazer',
      'Body-skimming modern dress',
      'Satin or draped top',
      'Current statement shoes',
      'Feminine midi skirt',
      'On-trend jewelry',
      'Chic statement coat',
      'Luxury handbag',
    ],
    beautyRoutine: 'Soft glamour suits you beautifully. Think glowing flattering lip. Your hair should have movement—s that still feels feminine Avoid anything overly severe. Even when your b softness and sensuality',
  },
  'Romantic/Dramatic': {
    name: 'The Bohemian',
    descriptor: 'Enchanting – Exotic - Presence',
    styleIcons: [
      'Helena Bonham Carter',
      'Stevie Nicks',
      'Helena Christensen',
      'Brigitte Bardot',
      'Nichole Richie',
    ],
    elements: [
      'Sculptural Cuts',
      'Unabashed Femininity',
      'Items that make a statement',
      'Conversation pieces',
    ],
    shadowSide: [
      'Trying too hard',
      'Overkill',
      'Hiding your shape',
      'Letting clothes wear you',
    ],
    statement: 'Enchanting Elegance',
    hallmarks: [
      'Black and neutrals mixed together in unexpected ways',
      'Florals, mixed prints',
      'Deep, rich hues',
      'Softened lines blended with crisp styles',
      'Layers',
      'Enchanting combinations',
    ],
    topTen: [
      'Sculptural statement jacket',
      'Flowing floral dress',
      'Embellished or embroidered',
      'tops',
      'Elegant flowing trousers',
      'Asymmetrical skirt',
      'Conversation-starting handbag',
      '& accessories',
      'Boots, boots, boots!',
      'Vintage & handcrafted jewelry',
      'Lace or sheer accents',
      'Layered maxi skirt',
    ],
    beautyRoutine: 'A layered hairstyle suits you, with soft wisps of hair to temper your dramatic side. Your haircolor is rich, yet subtle Makeup is soft and feminine with a strong eye or lip color as a focal point Keep your colors smoky and muted, yet choose deep, rich shades for lips, eyes and nails',
  },
  'Romantic/Sporty': {
    name: 'The Flirt',
    descriptor: 'Feminine, Playful, Energetic',
    styleIcons: [
      'Kate Hudson',
      'Jennifer Lopez',
      'Goldie Hawn',
      'Sofia Vergara',
      'Eva Longoria',
    ],
    elements: [
      'Feminine details',
      'Body-conscious silhouettes',
      'Comfortable fabrics',
      'Ease of movement',
    ],
    shadowSide: [
      'Looking too girlish',
      'Showing too much',
      'Sacrificing comfort for sex appeal',
      'Looking overly casual',
    ],
    statement: 'Effortless Allure',
    hallmarks: [
      'Body-skimming knits',
      'Feminine necklines',
      'Soft, stretchy fabrics',
      'Flirty dresses and skirts',
      'Great-fitting jeans',
      'Feminine athletic-inspired pieces',
      'Sexy-but-comfortable shoes',
      'Casual pieces that show your shape',
      'This differentiates her nicely from The Impulsive\' shoes and relaxed jackets',
    ],
    topTen: [
      'Body-skimming knit tops',
      'Great-fitting jeans',
      'Romantic blouse',
      'Sexy jersey dress',
      'Flirty knit skirt',
      'Feminine sneakers',
      'Leggings or fitted stretch pants',
      'Soft fitted cardigan',
      'Feminine casual jacket',
    ],
    beautyRoutine: 'Keep your beauty look pretty, fresh and effortle glossy or softly colored lip suit you beautifully Hair should have movement and touchability—so style that never looks overly “done.”',
  },
  'Sporty/Delicate': {
    name: 'The Subdued',
    descriptor: 'Informal, Refined, Reserved',
    styleIcons: [
      'Kristen Bell',
      'Halle Berry',
      'Michelle Williams',
      'Marisa Tomei',
    ],
    elements: [
      'Fabrics with Stretch',
      'Comfort',
      'Understated Femininity',
      'Unfussy details',
    ],
    shadowSide: [
      'Looking boring',
      'Looking frumpy',
      'Dressing too youthful',
      'Being overpowered by clothing',
      'Hiding your shape',
    ],
    statement: 'Sleek and Chic',
    hallmarks: [
      'Easy care separates that are machine wash, wrinkle resistant',
      'Functional shoes',
      'Fabrics with ease such as knits',
      'Feminine cuts',
      'Body conscious styles',
      'Relaxed jackets',
      'Easy fit, avoiding anything that is restricting',
    ],
    topTen: [
      'Ponte knit blazer',
      'Fine-knit cardigan',
      'Sleek leggings',
      'Delicate knit tops',
      'Simple jersey dress',
      'Refined sporty flats',
      'Easy-fit stretch pants',
      'Chic low wedges',
      'Relaxed lightweight jacket',
      'Delicate sneakers',
    ],
    beautyRoutine: 'Opt for easy care hair and soft, delicate makeup. Hair may be long or short, with great highlights and a bit of sexy movement. Your look is soft and feminine, yet easy care If you’re not much of a makeup wearer, try wearing just a few basics to add some color and polish to your look and boost your image',
  },
  'Sporty/Natural': {
    name: 'The Elemental',
    descriptor: 'Comfortable, Authentic, Fresh, ',
    styleIcons: [
      'Alicia Keys',
      'Sandra Bullock',
      'Carolyn Murphy',
      'Cameron Diaz',
    ],
    elements: [
      'Fabrics with Stretch',
      'Comfort',
      'Fabrics that feel good to the touch',
    ],
    shadowSide: [
      'Looking boring',
      'Looking frumpy',
      'In a rut',
      'Lack of style',
      'Hiding your shape',
    ],
    statement: 'Comfort Chic',
    hallmarks: [
      'Easy care separates that are machine wash, wrinkle resistant',
    ],
    topTen: [],
    beautyRoutine: 'Opt for easy care hair and soft, pretty makeup. Hair may be long or short, with great highlights, but nothing too dramatic. Stick with something simple and flattering If you’re not much of a makeup wearer, try wearing just a few basics to add some color and polish to your look and boost your image Ponte knit blazer Soft knit cardigan Sleek leggings Easy jersey dress Fitted knit tops Driving moccasins Easy-fit stretch pants Well-fitting jeans Functional utility jacket Elevated sneakers',
  },
  'Sporty/Romantic': {
    name: 'The Impulsive',
    descriptor: 'Energetic, Confident, Impetuous',
    styleIcons: [
      'Naomi Osaka',
      'Serena Williams',
      'Lindsey Vonn',
      'J. Lo',
    ],
    elements: [
      'Fabrics with Stretch',
      'Comfort',
      'Unabashedly Feminine',
      'Sense of History',
    ],
    shadowSide: [
      'Looking boring',
      'Looking frumpy',
      'Overkill',
      'Overpowering looks',
      'Hiding your shape',
    ],
    statement: 'Sexy Comfort',
    hallmarks: [
      'Easy care separates that are machine wash, wrinkle resistant',
      'Functional shoes',
      'Fabrics with ease such as knits',
      'Feminine cuts',
      'Body conscious styles',
      'Relaxed jackets',
      'Easy fit, avoiding anything that is restricting',
    ],
    topTen: [
      'Ponte knit blazer',
      'Soft knit cardigan',
      'Leggings',
      'Romantic tops',
      'Feminine jersey dress',
      'Driving moccasins',
      'Easy-fit pants with stretch',
      'Sporty watch',
      'Feminine fitted jacket',
      'Flirty knit skirt',
    ],
    beautyRoutine: 'Opt for easy care hair and soft, pretty makeup. Hair may be long or short, with great highlights, but nothing too dramatic. Stick with something simple and flattering If you’re not much of a makeup wearer, try wearing just a few basics to add some color and polish to your look and boost your image',
  },
  'Sporty/Whimsical': {
    name: 'The Playful Muse',
    descriptor: 'Playful, Jaunty, Rich',
    styleIcons: [
      'Jessica Alba',
      'Michelle Williams',
      'Kelly Osborne',
      'Kate Hudson',
    ],
    elements: [
      'Playfulness',
      'Unexpected Combinations',
      'Comfort',
      'Ease of movement',
    ],
    shadowSide: [
      'Looking too youthful',
      'Looking silly',
      'Frumpy',
      'Wearing oversized clothing',
    ],
    statement: 'Eclectic Chic',
    hallmarks: [
      'Styles that allow for movement',
      'Fun, playful accessories',
      'Luxurious fabrics',
      'Layered looks',
      'Bold color combinations',
      'Unexpected pairings',
      'Fun and surprise',
    ],
    topTen: [
      'Colorful tops',
      'Cozy cardigans',
      'Ponte knit trousers',
      'Knit wrap dress',
      'Ponte knit jacket',
      'Embellished flats',
      'Playful jewelry & accessories',
      'Fun statement handbag',
      'Coat in a bright hue',
      'Dark-wash denim',
    ],
    beautyRoutine: 'Hair and makeup are simple yet polished. You like to add a fun pop of color on eyes, lips or nails, but otherwise your look is understated and minimal You like for your hair to look good yet are not willing to spend much time on it. Opt for a cut that gives you the convenience of wash and go without sacrificing your style',
  },
  'Whimsical/Classic': {
    name: 'The Spirited',
    descriptor: 'Playful, Polished, Charming',
    styleIcons: [
      'Olivia Palermo',
      'Emma Stone',
      'Kate Spade',
      'Jenna Lyons',
    ],
    elements: [
      'Playful sophistication',
      'Polished silhouettes',
      'Unexpected details',
      'Color & pattern',
    ],
    shadowSide: [
      'Looking too prim',
      'Looking too youthful',
      'Over-coordinating',
      'Playing it too safe',
    ],
    statement: 'Polished Playfulness',
    hallmarks: [
      'Classic pieces with an unexpected twist',
      'Playful prints and patterns',
      'Crisp, polished silhouettes',
      'Interesting color combinations',
      'Statement shoes and handbags',
      'Clever accessories',
      'Mixing timeless and unexpected pieces',
    ],
    topTen: [
      'Playful tailored blazer',
      'Printed button-down blouse',
      'Chic patterned trousers',
      'Colorful cardigan',
      'Classic dress with an unexpected detail',
      'Embellished loafers or flats',
      'Statement jewelry',
      'Whimsical structured handbag',
      'Classic coat in a surprising color',
      'Dark-wash straight-leg jeans',
    ],
    beautyRoutine: 'Your beauty look is polished, fresh and feminine with a touch of fun. You appreciate beautifully groomed hair and natural-looking makeup, but enjoy an unexpected pop—a bright lip, colorful nail, interesting glasses or playful accessory Keep your hairstyle polished and intentional, but never overly stiff. A classic cut with movement and personality suits you beautifully',
  },
  'Whimsical/Contemporary': {
    name: 'The Fanciful',
    descriptor: 'Eclectic – Elegant - Intrigue',
    styleIcons: [
      'Betsy Johnson',
      'Zandra Rhodes',
      'Vivienne Westwood',
      'Chloe Sevigny',
    ],
    elements: [
      'Playfulness',
      'Unexpected Combinations',
      'Looking on Trend',
      'Wearing the Hottest Colors',
    ],
    shadowSide: [
      'Looking too youthful',
      'Looking silly',
      'Keeping up with the Joneses',
      'Looking too trendy',
    ],
    statement: 'Eclectic Chic',
    hallmarks: [
      'Styles that are on trend',
      'Fun, playful accessories',
      'Luxurious fabrics',
      'Short over long',
      'Bold color combinations',
      'Unexpected pairings',
      'Fun and surprise',
    ],
    topTen: [
      'Playful statement jacket',
      'Embellished cardigan',
      'Chic printed trousers',
      'Tops in bold hues',
      'Trendy statement dress',
      'Platform shooties',
      'Bold jewelry & accessories',
      'Statement handbag',
      'Coat in a bright hue',
      'Dark-wash denim',
    ],
    beautyRoutine: 'You have fun with your hair and makeup and use them to punctuate',
  },
  'Whimsical/Dramatic': {
    name: 'The Creative',
    descriptor: 'Spirited, Passionate, Purposeful',
    styleIcons: [
      'Katy Perry',
      'Nancy Cunard',
      'Dita von Teese,',
    ],
    elements: [
      'Playfulness',
      'Being Unique',
      'Something Unexpected',
      'Making a Statement',
    ],
    shadowSide: [
      'Looking too youthful',
      'Looking silly',
      'Letting clothing wear you',
      'Wearing something inappropriate',
    ],
    statement: 'Edgy Fun',
    hallmarks: [
      'Styles that stand out',
      'Sculptural cuts',
      'Fun, playful accessories',
      'Dramatic cuts',
      'Bold color combinations',
      'Unexpected pairings',
      'Fun and surprise',
    ],
    topTen: [
      'Playful statement jacket',
      'Embellished cardigan',
      'Chic printed skirt',
      'Tops in bold hues',
      'Architectural dress',
    ],
    beautyRoutine: 'You have fun with your hair and makeup and use them to punctuate',
  },
  'Whimsical/Sporty': {
    name: 'The Clever',
    descriptor: 'Playful, Jaunty, Rich',
    styleIcons: [
      'Jessica Alba',
      'Gwen Stefani',
      'Kelly Osborne',
      'Zooey Deschanel',
    ],
    elements: [
      'Playfulness',
      'Unexpected Combinations',
      'Comfort',
      'Ease of movement',
    ],
    shadowSide: [
      'Looking too youthful',
      'Looking silly',
      'Frumpy',
      'Wearing oversized clothing',
    ],
    statement: 'Eclectic Chic',
    hallmarks: [
      'Styles that allow for movement',
      'Fun, playful accessories',
      'Luxurious fabrics',
      'Layered looks',
      'Bold color combinations',
      'Unexpected pairings',
      'Fun and surprise',
    ],
    topTen: [
      'Colorful or printed tops',
      'Playful cardigans',
      'Patterned ponte trousers',
      'Fun knit dress',
      'Cropped ponte jacket',
      'Embellished flats or sneakers',
      'Playful statement jewelry',
      'Conversation-starting handbag',
      'Coat in a bright hue or print',
      'Colored or embellished denim',
    ],
    beautyRoutine: 'Hair and makeup are simple yet polished. You like to add a fun pop of color on eyes, lips or nails, but otherwise your look is understated and minimal You like for your hair to look good yet you want it to be easy. Opt for a cut that gives you the convenience of wash-and-go without sacrificing your style',
  },
};
